sudo: required
language: node_js
services:
  - docker
script:
  - docker-compose config
  - if [ $TRAVIS_BRANCH == 'unstable' ];
    then docker-compose build;
    else echo skipping build...;
    fi
