version: "2.3"
services:
  rust-server:
    volumes:
      - ~/volumes/rust-server/:/opt/rustserver/server/rust
    cpuset: '0'
    mem_reservation: 2048m
    build:
      context: .
    env_file:
      - vars.env
    ports:
    - "28015:28015/udp"
    - "28016:28016"
