version: "2.3"
services:
  rust-server:
    volumes:
      - type: bind
        source: ./rust/
        target: /opt/rustserver/server/rust
      - type: bind
        source: ./rust/server.log
        target: /opt/rustserver/server.log
#    cpuset: 2-3
    mem_reservation: 3000m
    build:
      context: .
    env_file:
      - vars.env
    ports:
    - "28025:28025/udp"
    - "28026:28026"
networks:
  default:
    external:
      name: egeeio_network
