version: "2.3"
services:
  rust-server:
    volumes:
      - type: bind
        source: ./server_files/
        target: /home/gsc/server_files
    # cpuset: 0-1
    mem_reservation: 3000m
    build:
      context: .
    env_file:
      - vars.env
    ports:
    - "28015:28015/udp"
    - "28016:28016"
