version: "2.3"
services:
  rust-server:
    volumes:
      # https://github.com/docker/compose/issues/3270
      - ~/volumes/rust-server/:/opt/rustserver/server/rust:Z
    cpuset: 0-1
    mem_reservation: 2048m
    build:
      context: .
    env_file:
      - vars.env
    ports:
    - "28015:28015/udp"
    - "28016:28016"
